# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433fdbe651f1a3bffd8944fa2637892227f0c97e2451ed4013378e8feac3904c6a9caa93ef36f2f92173d08ad243cb220eb6a790f3a885f131ea7ce78c0d0273

test:
  secret_key_base: 735d4bb55afa327afd404f675a2e4429a50d471b0371946d9c35c7264834ddcb77e2a11dc119a14bc52c9e4cba3ebeab73adec6e0dcca041e87c480048fac056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
